# Generated by Django 6.0.6 on 2026-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
